# Generated by Django 5.1.5 on 2025-01-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformacurriculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-Mail')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('posicao_desejada', models.CharField(max_length=100, verbose_name='Posição Desejada')),
                ('escolaridade', models.CharField(choices=[('ensino_medio', 'Ensino Médio'), ('graduacao', 'Graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=100, verbose_name='Escolaridade')),
                ('observacoes', models.TextField(max_length=100, verbose_name='Observações')),
                ('curriculo', models.FileField(upload_to='projsesap/plataformacurriculos/curriculos', verbose_name='Carregar o Currículo')),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
