# Generated by Django 5.1.5 on 2025-01-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformacurriculos', '0002_curriculo_delete_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curriculo',
            old_name='posicao_desejada',
            new_name='cargodesejado',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='nome',
        ),
        migrations.AddField(
            model_name='curriculo',
            name='primeironome',
            field=models.CharField(default='Danilo', max_length=100, verbose_name='Primeiro Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculo',
            name='ultimonome',
            field=models.CharField(default='Ladeira', max_length=100, verbose_name='Último Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='escolaridade',
            field=models.CharField(choices=[('ensino_medio', 'Ensino Médio'), ('graduacao', 'Graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=20, verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='observacoes',
            field=models.TextField(verbose_name='Observações'),
        ),
    ]
