# Generated by Django 5.1.5 on 2025-01-28 02:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataformacurriculos', '0003_rename_posicao_desejada_curriculo_cargodesejado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
